name: CI-CD OpenShift

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar OpenShift CLI
        uses: redhat-actions/oc-installer@v1

      - name: Iniciar sesión en OpenShift
        run: |
          oc login "${{ secrets.OPENSHIFT_SERVER }}" \
            --token="${{ secrets.OPENSHIFT_TOKEN }}" \
            --insecure-skip-tls-verify=true

      - name: Seleccionar proyecto
        run: |
          oc project martingallardo-dev

      - name: Iniciar build
        run: |
          oc start-build practico-1-git --follow

      - name: Actualizar aplicación Serverless
          run: |
            IMAGE=$(oc get istag practico-1-git:latest -o jsonpath='{.image.dockerImageReference}')
        
            echo "Nueva imagen: $IMAGE"
        
            oc patch ksvc practico-1-git \
              --type='merge' \
              -p "{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"practico-1-git\",\"image\":\"$IMAGE\"}]}}}}"
